-- Script de criação de tabelas
-- Banco de dados: NEGOCIACOES.FDB
-- Firebird 2.1

CONNECT 'C:\NEGOCIACOES.FDB' USER 'SYSDBA' PASSWORD 'masterkey';

-- Tabela: PRODUTOR
CREATE TABLE PRODUTOR (
    ID INTEGER NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CPF_CNPJ VARCHAR(18) NOT NULL,
    CONSTRAINT PK_PRODUTOR PRIMARY KEY (ID)
);

-- Tabela: DISTRIBUIDOR
CREATE TABLE DISTRIBUIDOR (
    ID INTEGER NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CNPJ VARCHAR(18) NOT NULL,
    CONSTRAINT PK_DISTRIBUIDOR PRIMARY KEY (ID)
);

-- Tabela: PRODUTO
CREATE TABLE PRODUTO (
    ID INTEGER NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    PRECO_VENDA NUMERIC(15,2) NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (ID)
);

-- Tabela: LIMITE_CREDITO
CREATE TABLE LIMITE_CREDITO (
    ID INTEGER NOT NULL,
    ID_PRODUTOR INTEGER NOT NULL,
    ID_DISTRIBUIDOR INTEGER NOT NULL,
    VALOR_LIMITE NUMERIC(15,2) NOT NULL,
    CONSTRAINT PK_LIMITE_CREDITO PRIMARY KEY (ID),
    CONSTRAINT FK_LIMITE_PRODUTOR FOREIGN KEY (ID_PRODUTOR) REFERENCES PRODUTOR(ID),
    CONSTRAINT FK_LIMITE_DISTRIBUIDOR FOREIGN KEY (ID_DISTRIBUIDOR) REFERENCES DISTRIBUIDOR(ID)
);

-- Tabela: STATUS_NEGOCIACAO
CREATE TABLE STATUS_NEGOCIACAO (
    ID INTEGER NOT NULL,
    DESCRICAO VARCHAR(20) NOT NULL,
    CONSTRAINT PK_STATUS_NEGOCIACAO PRIMARY KEY (ID)
);

-- Tabela: NEGOCIACAO
CREATE TABLE NEGOCIACAO (
    ID INTEGER NOT NULL,
    ID_PRODUTOR INTEGER NOT NULL,
    ID_DISTRIBUIDOR INTEGER NOT NULL,
    DATA_CADASTRO TIMESTAMP NOT NULL,
    DATA_APROVACAO TIMESTAMP,
    DATA_CONCLUSAO TIMESTAMP,
    DATA_CANCELAMENTO TIMESTAMP,
    VALOR_TOTAL NUMERIC(15,2) NOT NULL,
    STATUS INTEGER NOT NULL,
    CONSTRAINT PK_NEGOCIACAO PRIMARY KEY (ID),
    CONSTRAINT FK_NEGOCIACAO_PRODUTOR FOREIGN KEY (ID_PRODUTOR) REFERENCES PRODUTOR(ID),
    CONSTRAINT FK_NEGOCIACAO_DISTRIBUIDOR FOREIGN KEY (ID_DISTRIBUIDOR) REFERENCES DISTRIBUIDOR(ID),
    CONSTRAINT FK_NEGOCIACAO_STATUS FOREIGN KEY (STATUS) REFERENCES STATUS_NEGOCIACAO(ID)
);

-- Tabela: ITEM_NEGOCIACAO
CREATE TABLE ITEM_NEGOCIACAO (
    ID INTEGER NOT NULL,
    ID_NEGOCIACAO INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
    QUANTIDADE NUMERIC(10,2) NOT NULL,
    PRECO_UNITARIO NUMERIC(15,2) NOT NULL,
    VALOR_TOTAL NUMERIC(15,2) NOT NULL,
    CONSTRAINT PK_ITEM_NEGOCIACAO PRIMARY KEY (ID),
    CONSTRAINT FK_ITEM_NEGOCIACAO FOREIGN KEY (ID_NEGOCIACAO) REFERENCES NEGOCIACAO(ID),
    CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID)
);

-- Generator para PRODUTOR
CREATE GENERATOR GEN_PRODUTOR_ID;

-- Generator para DISTRIBUIDOR
CREATE GENERATOR GEN_DISTRIBUIDOR_ID;

-- Generator para PRODUTO
CREATE GENERATOR GEN_PRODUTO_ID;

-- Generator para LIMITE_CREDITO
CREATE GENERATOR GEN_LIMITE_CREDITO_ID;

-- Generator para NEGOCIACAO
CREATE GENERATOR GEN_NEGOCIACAO_ID;

-- Generator para ITEM_NEGOCIACAO
CREATE GENERATOR GEN_ITEM_NEGOCIACAO_ID;

-- Trigger para auto-incremento de PRODUTOR
SET TERM ^ ;
CREATE TRIGGER TRG_PRODUTOR_BI FOR PRODUTOR
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_PRODUTOR_ID, 1);
END
^
SET TERM ; ;

-- Trigger para auto-incremento de DISTRIBUIDOR
SET TERM ^ ;
CREATE TRIGGER TRG_DISTRIBUIDOR_BI FOR DISTRIBUIDOR
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_DISTRIBUIDOR_ID, 1);
END
^
SET TERM ; ;

-- Trigger para auto-incremento de PRODUTO
SET TERM ^ ;
CREATE TRIGGER TRG_PRODUTO_BI FOR PRODUTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_PRODUTO_ID, 1);
END
^
SET TERM ; ;

-- Trigger para auto-incremento de LIMITE_CREDITO
SET TERM ^ ;
CREATE TRIGGER TRG_LIMITE_CREDITO_BI FOR LIMITE_CREDITO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_LIMITE_CREDITO_ID, 1);
END
^
SET TERM ; ;

-- Trigger para auto-incremento de NEGOCIACAO
SET TERM ^ ;
CREATE TRIGGER TRG_NEGOCIACAO_BI FOR NEGOCIACAO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_NEGOCIACAO_ID, 1);
END
^
SET TERM ; ;

-- Trigger para auto-incremento de ITEM_NEGOCIACAO
SET TERM ^ ;
CREATE TRIGGER TRG_ITEM_NEGOCIACAO_BI FOR ITEM_NEGOCIACAO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_ITEM_NEGOCIACAO_ID, 1);
END
^
SET TERM ; ;

COMMIT;
QUIT;
