-- Script de criação de tabelas
-- Banco de dados: NEGOCIACOES.FDB
-- Firebird 2.1
-- Ajustado conforme as entidades, interfaces e repositórios do projeto

CONNECT 'C:\Aliari\DesafioNegociacao\data\database\NEGOCIACOES.FDB'
USER 'SYSDBA' PASSWORD 'masterkey';

/* ============================================================
   TABELAS PRINCIPAIS
   ============================================================ */

-- Tabela: PRODUTOR
CREATE TABLE PRODUTOR (
    ID INTEGER NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CPF_CNPJ VARCHAR(18) NOT NULL,
    CONSTRAINT PK_PRODUTOR PRIMARY KEY (ID)
);

-- Tabela: DISTRIBUIDOR
CREATE TABLE DISTRIBUIDOR (
    ID INTEGER NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CNPJ VARCHAR(18) NOT NULL,
    CONSTRAINT PK_DISTRIBUIDOR PRIMARY KEY (ID)
);

-- Tabela: PRODUTO
CREATE TABLE PRODUTO (
    ID INTEGER NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    PRECO_VENDA NUMERIC(15,2) NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (ID)
);

-- Tabela de relacionamento entre distribuidor e produto.
-- O valor do produto pode variar de acordo com o distribuidor.
CREATE TABLE DISTRIBUIDOR_PRODUTO (
    ID INTEGER NOT NULL,
    ID_DISTRIBUIDOR INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
    VALOR_PRODUTO NUMERIC(15,2) NOT NULL,
    CONSTRAINT PK_DISTRIBUIDOR_PRODUTO PRIMARY KEY (ID),
    CONSTRAINT FK_DIST_PROD_DISTRIBUIDOR
        FOREIGN KEY (ID_DISTRIBUIDOR) REFERENCES DISTRIBUIDOR (ID),
    CONSTRAINT FK_DIST_PROD_PRODUTO
        FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID),
    CONSTRAINT UK_DISTRIBUIDOR_PRODUTO
        UNIQUE (ID_DISTRIBUIDOR, ID_PRODUTO)
);

-- Tabela de limite de crédito do produtor por distribuidor.
CREATE TABLE PRODUTOR_LIMITE_CREDITO (
    ID INTEGER NOT NULL,
    ID_PRODUTOR INTEGER NOT NULL,
    ID_DISTRIBUIDOR INTEGER NOT NULL,
    VALOR_LIMITE NUMERIC(15,2) NOT NULL,
    CONSTRAINT PK_PROD_LIMITE_CREDITO PRIMARY KEY (ID),
    CONSTRAINT FK_PROD_LIMITE_PRODUTOR
        FOREIGN KEY (ID_PRODUTOR) REFERENCES PRODUTOR (ID),
    CONSTRAINT FK_PROD_LIMITE_DISTRIB
        FOREIGN KEY (ID_DISTRIBUIDOR) REFERENCES DISTRIBUIDOR (ID),
    CONSTRAINT UK_PROD_LIMITE_CREDITO
        UNIQUE (ID_PRODUTOR, ID_DISTRIBUIDOR)
);

-- Tabela: STATUS_NEGOCIACAO
-- Os IDs seguem o mapeamento utilizado em TNegociacaoRepositoryFB:
-- 1 = Pendente, 2 = Aprovada, 3 = Concluída, 4 = Cancelada.
CREATE TABLE STATUS_NEGOCIACAO (
    ID INTEGER NOT NULL,
    DESCRICAO VARCHAR(20) NOT NULL,
    CONSTRAINT PK_STATUS_NEGOCIACAO PRIMARY KEY (ID),
    CONSTRAINT UK_STATUS_NEGOCIACAO UNIQUE (DESCRICAO)
);

-- Tabela: NEGOCIACAO
CREATE TABLE NEGOCIACAO (
    ID INTEGER NOT NULL,
    ID_PRODUTOR INTEGER NOT NULL,
    ID_DISTRIBUIDOR INTEGER NOT NULL,
    DATA_CADASTRO TIMESTAMP NOT NULL,
    DATA_APROVACAO TIMESTAMP,
    DATA_CONCLUSAO TIMESTAMP,
    DATA_CANCELAMENTO TIMESTAMP,
    VALOR_TOTAL NUMERIC(15,2) NOT NULL,
    STATUS INTEGER NOT NULL,
    CONSTRAINT PK_NEGOCIACAO PRIMARY KEY (ID),
    CONSTRAINT FK_NEGOCIACAO_PRODUTOR
        FOREIGN KEY (ID_PRODUTOR) REFERENCES PRODUTOR (ID),
    CONSTRAINT FK_NEGOCIACAO_DISTRIB
        FOREIGN KEY (ID_DISTRIBUIDOR) REFERENCES DISTRIBUIDOR (ID),
    CONSTRAINT FK_NEGOCIACAO_STATUS
        FOREIGN KEY (STATUS) REFERENCES STATUS_NEGOCIACAO (ID)
);

-- Tabela: NEGOCIACAO_ITEM
-- Nome utilizado pelo repositório ativo TNegociacaoItemRepositoryFB.
CREATE TABLE NEGOCIACAO_ITEM (
    ID INTEGER NOT NULL,
    ID_NEGOCIACAO INTEGER NOT NULL,
    ID_PRODUTO INTEGER NOT NULL,
    QUANTIDADE NUMERIC(10,2) NOT NULL,
    PRECO_UNITARIO NUMERIC(15,2) NOT NULL,
    VALOR_TOTAL NUMERIC(15,2) NOT NULL,
    CONSTRAINT PK_NEGOCIACAO_ITEM PRIMARY KEY (ID),
    CONSTRAINT FK_NEG_ITEM_NEGOCIACAO
        FOREIGN KEY (ID_NEGOCIACAO) REFERENCES NEGOCIACAO (ID),
    CONSTRAINT FK_NEG_ITEM_PRODUTO
        FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID)
);

COMMIT;

/* ============================================================
   GENERATORS
   ============================================================ */

CREATE GENERATOR GEN_PRODUTOR_ID;
CREATE GENERATOR GEN_DISTRIBUIDOR_ID;
CREATE GENERATOR GEN_PRODUTO_ID;
CREATE GENERATOR GEN_DISTRIBUIDOR_PRODUTO_ID;
CREATE GENERATOR GEN_PROD_LIMITE_CREDITO_ID;
CREATE GENERATOR GEN_NEGOCIACAO_ID;
CREATE GENERATOR GEN_NEGOCIACAO_ITEM_ID;

COMMIT;

/* ============================================================
   TRIGGERS DE AUTO-INCREMENTO
   ============================================================ */

SET TERM ^ ;

CREATE TRIGGER TRG_PRODUTOR_BI FOR PRODUTOR
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_PRODUTOR_ID, 1);
END^

CREATE TRIGGER TRG_DISTRIBUIDOR_BI FOR DISTRIBUIDOR
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_DISTRIBUIDOR_ID, 1);
END^

CREATE TRIGGER TRG_PRODUTO_BI FOR PRODUTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_PRODUTO_ID, 1);
END^

CREATE TRIGGER TRG_DISTRIB_PRODUTO_BI FOR DISTRIBUIDOR_PRODUTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_DISTRIBUIDOR_PRODUTO_ID, 1);
END^

CREATE TRIGGER TRG_PROD_LIMITE_CREDITO_BI FOR PRODUTOR_LIMITE_CREDITO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_PROD_LIMITE_CREDITO_ID, 1);
END^

CREATE TRIGGER TRG_NEGOCIACAO_BI FOR NEGOCIACAO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_NEGOCIACAO_ID, 1);
END^

CREATE TRIGGER TRG_NEGOCIACAO_ITEM_BI FOR NEGOCIACAO_ITEM
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_NEGOCIACAO_ITEM_ID, 1);
END^

SET TERM ; ^

COMMIT;

/* ============================================================
   REGISTROS INICIAIS
   ============================================================ */

INSERT INTO STATUS_NEGOCIACAO (ID, DESCRICAO)
VALUES (1, 'Pendente');

INSERT INTO STATUS_NEGOCIACAO (ID, DESCRICAO)
VALUES (2, 'Aprovada');

INSERT INTO STATUS_NEGOCIACAO (ID, DESCRICAO)
VALUES (3, 'Concluida');

INSERT INTO STATUS_NEGOCIACAO (ID, DESCRICAO)
VALUES (4, 'Cancelada');

COMMIT;
QUIT;
