-- Script de inserts iniciais
-- Banco de dados: NEGOCIACOES.FDB
-- Firebird 2.1

CONNECT 'C:\NEGOCIACOES.FDB' USER 'SYSDBA' PASSWORD 'masterkey';

-- Inserir status de negociação
INSERT INTO STATUS_NEGOCIACAO (ID, DESCRICAO) VALUES (1, 'Pendente');
INSERT INTO STATUS_NEGOCIACAO (ID, DESCRICAO) VALUES (2, 'Aprovada');
INSERT INTO STATUS_NEGOCIACAO (ID, DESCRICAO) VALUES (3, 'Concluida');
INSERT INTO STATUS_NEGOCIACAO (ID, DESCRICAO) VALUES (4, 'Cancelada');

COMMIT;
QUIT;
